Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AEHKT.Common;
using AEHKT.Models;

namespace AEHKT.Areas.Admin.Controllers
{

    public class CategoryController : BaseController
    {
        private AEHKTDbContext db = new AEHKTDbContext();

        // GET: Admin/Category
        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        public ActionResult Index()
        {
         
            ViewBag.listCate = db.Categorys.Where(m => m.status != 0).ToList();
            var list = db.Categorys.Where(m => m.status > 0).ToList();
            return View(list);
        }
        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        // GET: Admin/Category/Create
        public ActionResult Create()
        {
            
            ViewBag.listCate = db.Categorys.Where(m => m.status !=0 ).ToList();
            return View();
        }
        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Mcategory mcategory)
        {
          
            if (ModelState.IsValid)
            {
                //category
                string slug = Mystring.ToSlug(mcategory.name.ToString());
                if (db.Categorys.Where(m=>m.slug == slug).Count()>0) {
                    Message.set_flash("Loại sản phẩm đã tồn tại trong bảng Category", "danger");
                    return View(mcategory);
                }
                //topic
              
                if (db.topics.Where(m => m.slug == slug).Count() > 0)
                {
                    Message.set_flash("Loại sản phẩm đã tồn tại trong bảng Topic", "danger");
                    return View(mcategory);
                }
                if (db.Products.Where(m => m.slug == slug).Count() > 0)
                {
                    Message.set_flash("Loại sản phẩm đã tồn tại trong bảng Product", "danger");
                    return View(mcategory);
                }
                mcategory.slug = slug;
                mcategory.created_at = DateTime.Now;
                mcategory.updated_at = DateTime.Now;
                mcategory.created_by = int.Parse(Session["Admin_id"].ToString());
                mcategory.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.Categorys.Add(mcategory);
                db.SaveChanges();
                Message.set_flash("Thêm  thành công", "success");
                return RedirectToAction("index");
            }
            Message.set_flash("Thêm  Thất Bại", "danger");
            ViewBag.listCate = db.Categorys.Where(m => m.status != 0).ToList();
            return View(mcategory);
        }
        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        // GET: Admin/Category/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.listCate = db.Categorys.Where(m => m.status != 0).ToList();
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mcategory mcategory = db.Categorys.Find(id);
            if (mcategory == null)
            {
                return HttpNotFound();
            }
            return View(mcategory);
        }

        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit( Mcategory mcategory)
        {
            if (ModelState.IsValid)
            {
                string slug = Mystring.ToSlug(mcategory.name.ToString());
                mcategory.slug = slug;
                mcategory.updated_at = DateTime.Now;
                mcategory.updated_by = int.Parse(Session["Admin_id"].ToString());
                db.Entry(mcategory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            Message.set_flash("Sửa thất bại", "success");
            return View(mcategory);
        }

        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        //status
        public ActionResult Status(int id)
        {
            Mcategory mcategory = db.Categorys.Find(id);
            mcategory.status = (mcategory.status == 1) ? 2 : 1;
            mcategory.updated_at = DateTime.Now;
            mcategory.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mcategory).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Thay đổi trạng thái thành công", "success");
            return RedirectToAction("Index");
        }
        [CustomAuthorizeAttribute(RoleID = "SALESMAN")]
        //trash
        public ActionResult trash()
        {
            var list = db.Categorys.Where(m => m.status == 0).ToList();
            return View("Trash", list);
        }
        public ActionResult Deltrash(int id)
        {
            Mcategory mcategory = db.Categorys.Find(id);
            mcategory.status =  0;
            mcategory.updated_at = DateTime.Now;
            mcategory.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mcategory).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Đã vào thùng rác", "success");
            return RedirectToAction("Index");
        }
       
        public ActionResult Retrash(int id)
        {
            Mcategory mcategory = db.Categorys.Find(id);
            mcategory.status = 2;
            mcategory.updated_at = DateTime.Now;
            mcategory.updated_by = int.Parse(Session["Admin_id"].ToString());
            db.Entry(mcategory).State = EntityState.Modified;
            db.SaveChanges();
            Message.set_flash("Khôi phục thành công !", "success");
            return RedirectToAction("trash");
        }
        public ActionResult deleteTrash(int id)
        {
            Mcategory mcategory = db.Categorys.Find(id);
            db.Categorys.Remove(mcategory);
            db.SaveChanges();
            Message.set_flash("Đã xóa vĩnh viễn 1 sản phẩm", "success");
            return RedirectToAction("trash");
        }

    }
}

Controllers/SanphamController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AEHKT.Models;
using PagedList;
namespace AEHKT.Controllers
{
    public class SanphamController : Controller
    {
        // GET: Sanpham
        AEHKTDbContext db = new AEHKTDbContext();
        public ActionResult index(int? page)
        {
            var list = db.Products.Where(m => m.status == 1).OrderBy(m=>m.ID);
            if (page == null) page = 1;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;
            return View(list.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult category(String slug)
        {
            var catid = db.Categorys.Where(m =>m.slug == slug && m.status == 1).First();
            return View(catid);
        }

        public ActionResult detail( String slug)
        {
            var list = db.Products.Where(m => m.status == 1 && m.slug == slug).First();
            return View(list);
        }
        public ActionResult cungloai(int catid)
        {
            var list = db.Products.Where(m => m.catid == catid && m.status == 1);
            return View("~/Views/Sanpham/_cungloai_detail.cshtml",list.ToList().Take(6));
        }
        public ActionResult subcategory(int catid,string slug, int? page)
        {
            var list = db.Products.Where(m => m.catid == catid || m.Submenu==catid && m.status == 1).OrderBy(m=>m.ID);
            if (page == null) page = 1;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;
            ViewBag.slug = slug;
            return View("~/Views/Sanpham/_Subcategory.cshtml", list.ToPagedList(pageNumber, pageSize));
        }
        public ActionResult SearchProduct(string keyw, int? page) {
            @ViewBag.keyw = keyw;
            if (page == null) page = 1;
            int pageSize = 8;
            int pageNumber = (page ?? 1);
            var list = db.Products.Where(m => m.status == 1 && m.name.Contains(keyw)).OrderBy(m => m.ID);
            return View("~/Views/Sanpham/_SearchProduct.cshtml", list.ToPagedList(pageNumber, pageSize));
        }

    }
}

Views/Sanpham/_SearchProduct.cshtml
@model PagedList.IPagedList<AEHKT.Models.Mproduct>
@using PagedList.Mvc;
@{
    ViewBag.Title = "San pham";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Mainmenu", "module")

<section class="container-fluid pt-3">
    <div class="container ">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("Listcategory", "module")
            </div>
            <div class="col-md-9">
                <div class="card ">
                    <h3 class="card-header text-xanhduong bg-white">Tìm Kiếm Sản Phẩm</h3>
                    <p>Các sản phẩm có tên "@ViewBag.keyw"</p>
                    <div class="card-body">
                        <div class="row">
                            @foreach (var item in Model)
                            {
                                int sale = (int)item.pricesale;
                                float price = (int)item.price - (int)item.price / 100 * (int)sale;
                                if (sale > 0)
                                {
                                    <div class="col-md-3 py-1 " style="padding-left: 5px; padding-right: 5px; ">
                                        <div class="card">
                                            <div class="card-body p-1">
                                                <div class="position-relative">
                                                    <div class="arrow-up">
                                                        <span class=" text-white pl-3">-@sale%</span>
                                                    </div>
                                                    <a href="~/sanpham/chitiet-sp/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                                                </div>
                                                <div class="card-title text-dark pt-2 align-content-center" style="margin-bottom: 0px;">
                                                    <h5 style="margin-bottom: 0px; text-align: center;">
                                                        <a href="~/sanpham/chitiet-sp/@item.slug" class="text-dark font-weight-bold " style="text-align:center;">
                                                            @item.name
                                                        </a>
                                                    </h5>
                                                </div>
                                                <div class="card-title text-dark">
                                                    <p class="font-weight-light" style="margin-bottom: 0px; text-align: center; font-size: 13px;"><strike> @item.price.ToString("N0") VND </strike></p>
                                                    <h6 class="font-weight-bold text-danger" style="text-align: center;">@price.ToString("N0") VND </h6>
                                                    <button id="addcartH" onclick="addcart(@item.ID)" type="button" class="btn-button-cart w-100 bg-dark btn-sm"> Mua Ngay</button>
                                                    <input type="hidden" value="1" id="sel1" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="col-md-3 py-1 " style="padding-left: 5px; padding-right: 5px; ">
                                        <div class="card">
                                            <div class="card-body p-1">
                                                <div class="position-relative">
                                                    <a href="~/sanpham/chitiet-sp/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                                                </div>
                                                <div class="card-title text-dark pt-2 align-content-center" style="margin-bottom: 0px;">
                                                    <h5 style="margin-bottom: 0px; text-align: center;">
                                                        <a href="~/sanpham/chitiet-sp/@item.slug" class="text-dark font-weight-bold " style="text-align:center;">
                                                            @item.name
                                                        </a>
                                                    </h5>
                                                </div>
                                                <div class="card-title text-dark">
                                                    <h6 class="font-weight-bold text-danger"  style="text-align: center;"> @item.price.ToString("N0") VND </h6>
                                                    <button id="addcartH" onclick="addcart(@item.ID)" type="button" class="btn-button-cart w-100  bg-dark btn-sm"> Mua Ngay</button>
                                                    <input type="hidden" value="1" id="sel1" />
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                }
                            }

                        </div>

                    </div>
                    <ul class="pagination pagination-sm justify-content-center">
                        @{ int i = 1;}

                        @for (int j = i; j <= Model.PageCount; j++)
                        {
                            <li class="page-item"><a class="page-link text-secondary  active-@j" href="/sanpham/?page=@j">@j</a></li>
                            i = j;
                        }
                    </ul>
                </div>

            </div>
        </div>
    </div>
</section>
<style>
    .active-@ViewBag.page{
    background-color: yellow;
    }
</style>

Views/Sanpham/_Subcategory.cshtml
@model PagedList.IPagedList<AEHKT.Models.Mproduct>

@foreach (var item in Model)
{
    int sale = (int)item.pricesale;
    float price = (int)item.price - (int)item.price / 100 * (int)sale;
    if (sale > 0)
    {
<div class="col-md-3 py-1 " style="padding-left: 5px; padding-right: 5px; ">
    <div class="card">
        <div class="card-body p-1">
            <div class="position-relative">
                <div class="arrow-up">
                    <span class=" text-white pl-3">-@sale%</span>
                </div>
                <a href="~/sanpham/chitiet-sp/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
            </div>
            <div class="card-title text-dark pt-2 align-content-center" style="margin-bottom: 0px;">
                <h5 style="margin-bottom: 0px; text-align: center;">
                    <a href="~/sanpham/chitiet-sp/@item.slug" class="text-dark font-weight-bold " style="text-align:center;">
                        @item.name
                    </a>
                </h5>
            </div>
            <div class="card-title text-dark">
                <p class="font-weight-light" style="margin-bottom: 0px; text-align: center; font-size: 13px;"><strike> @item.price.ToString("N0") VND </strike></p>
                <h6 class="font-weight-bold text-danger" style="text-align: center;">@price.ToString("N0") VND </h6>
                <button id="addcartH" onclick="addcart(@item.ID)" type="button" class="btn-button-cart w-100 bg-dark btn-sm"> Mua Ngay</button>
                <input type="hidden" value="1" id="sel1" />
            </div>
        </div>
    </div>
</div>
    }
    else
    {
<div class="col-md-3 py-1 " style="padding-left: 5px; padding-right: 5px; ">
    <div class="card">
        <div class="card-body p-1">
            <div class="position-relative">
                <a href="~/sanpham/chitiet-sp/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
            </div>
            <div class="card-title text-dark pt-2 align-content-center" style="margin-bottom: 0px;">
                <h5 style="margin-bottom: 0px; text-align: center;">
                    <a href="~/sanpham/chitiet-sp/@item.slug" class="text-dark font-weight-bold " style="text-align:center;">
                        @item.name
                    </a>
                </h5>
            </div>
            <div class="card-title text-dark">
                <h6 class="font-weight-bold text-danger" style="text-align: center;">@item.price.ToString("N0") VND </h6>
                <button id="addcartH" onclick="addcart(@item.ID)" type="button" class="btn-button-cart w-100 bg-dark btn-sm"> Mua Ngay</button>
                <input type="hidden" value="1" id="sel1" />
            </div>
        </div>
    </div>
</div>
    }
}

<div class="col-md-12 pt-3">
    <ul class="pagination pagination-sm justify-content-center">
        @{ int i = 1;}

        @for (int j = i; j <= Model.PageCount; j++)
        {
            <li class="page-item"><a class="page-link text-secondary  active-@j" href="/sanpham/loaiSP//@ViewBag.slug/?page=@j">@j</a></li>
            i = j;
        }
    </ul>
</div>


<style>
    .active-@ViewBag.page{
    background-color: yellow;
    }
</style>

Views/Sanpham/_cungloai_detail.cshtml
@model IEnumerable<AEHKT.Models.Mproduct>

@foreach (var item in Model)
{
    int sale = (int)item.pricesale;
    float price = (int)item.price - (int)item.price / 100 * (int)sale;
    if (sale > 0)
    {
        <div class="col-md-3 py-1 " style="padding-left: 5px; padding-right: 5px; ">
            <div class="card">
                <div class="card-body p-1">
                    <div class="position-relative">
                        <div class="arrow-up">
                            <span class=" text-white pl-3">-@sale%</span>
                        </div>
                        <a href="~/sanpham/chitiet-sp/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-2 align-content-center" style="margin-bottom: 0px;">
                        <h5 style="margin-bottom: 0px; text-align: center;">
                            <a href="~/sanpham/chitiet-sp/@item.slug" class="text-dark font-weight-bold " style="text-align:center;">
                                @item.name
                            </a>
                        </h5>
                    </div>
                    <div class="card-title text-dark">
                        <p class="font-weight-light" style="margin-bottom: 0px; text-align: center; font-size: 13px;"><strike> @item.price.ToString("N0") VND </strike></p>
                        <h6 class="font-weight-bold text-danger" style="text-align: center;">@price.ToString("N0") VND </h6>
                        <button id="addcartH" onclick="addcart(@item.ID)" type="button" class="btn-button-cart w-100 bg-dark btn-sm"> Mua Ngay</button>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="col-md-3 py-1 " style="padding-left: 5px; padding-right: 5px; ">
            <div class="card">
                <div class="card-body p-1">
                    <div class="position-relative">
                        <a href="~/sanpham/chitiet-sp/@item.slug"><img class="card-img-top" src="~/public/images/@item.img" alt="Card image"></a>
                    </div>
                    <div class="card-title text-dark pt-2 align-content-center" style="margin-bottom: 0px;">
                        <h5 style="margin-bottom: 0px; text-align: center;">
                            <a href="~/sanpham/chitiet-sp/@item.slug" class="text-dark font-weight-bold " style="text-align:center;">
                                @item.name
                            </a>
                        </h5>
                    </div>
                    <div class="card-title text-dark">
                        <h6 class="font-weight-bold text-danger" style="text-align: center;">@item.price.ToString("N0") VND </h6>
                        <button id="addcartH" onclick="addcart(@item.ID)" type="button" class="btn-button-cart w-100 bg-dark btn-sm"> Mua Ngay</button>
                        <input type="hidden" value="1" id="sel1" />
                    </div>
                </div>
            </div>
        </div>
    }
}

Views/Sanpham/category.cshtml
@model AEHKT.Models.Mcategory
@{
    ViewBag.Title = "loai san pham";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Mainmenu", "module")
<section class="container-fluid pt-3">
    <div class="container ">
        <div class="row">
            <div class="col-md-3">
                @Html.Action("Listcategory", "module")
            </div>
            <div class="col-md-9">
                <div class="card ">
                    <h3 class="card-header text-xanhduong bg-white">@Model.name</h3>
                    <div class="card-body">
                        <div class="row">
                            @Html.Action("subcategory", "Sanpham", new { catid = @Model.ID,slug = Model.slug })
                        </div>
                                </div>
                            </div>

                        </div>
        </div>`
    </div>
</section>

Views/Sanpham/detail.cshtml
@model AEHKT.Models.Mproduct
@{
    ViewBag.Title = "Chi tiet san pham";
    Layout = "~/Views/Shared/_LayoutSite.cshtml";
}
@Html.Action("Mainmenu", "module")
@{
    string detail = Model.detail;
    int number = Model.number;
    int sale = (int)Model.pricesale;
    float price = (int)Model.price - (int)Model.price / 100 * (int)sale;

    }
<section>
    <div class="container-fluid pt-5">
        <div class="container card bg-white">

            <div class="row  ">
                <div class="col-md-6">
                    @if (sale > 0)
                    {
                    <div class="py-4 pl-4 position-relative">
                        <div class="arrow-up">
                            <span class=" text-white pl-3">-@sale%</span>
                        </div>
                        <img class="img-fluid" src="~/public/images/@Model.img" alt="">
                    </div>
                    }
                    else
                    {
                        <div class="py-4 pl-4">
                            <img class="img-fluid" src="~/public/images/@Model.img" alt="">
                        </div>
                    }
                </div>
                <div class="col-md-6 pt-4 ">
                    <p class=" badge badge-danger"> New</p>
                    <ul class="list-unstyled ">
                        <li><p class="font-weight-bold font-16">@Model.name</p></li>
                        <li><p class="font-14"><span class="font-weight-bold">Mã Sản Phẩm:</span>@Model.ID</p></li>
                        
                        @if (sale > 0)
                        {
                            <li> <h4 class="font-weight-light" style="margin-bottom: 0px;  font-size: 20px;"><strike> Giá: @Model.price.ToString("N0") VND </strike><span class="text-warning"></span></h4>
                                 <h4 class="font-weight-bold text-danger">Giá: @price.ToString("N0") VND <span class="text-warning"></span></h4>
                        </li>
                        }
                        else
                        {
                            <li> <h4 class="font-weight-bold text-danger">Giá: @Model.price.ToString("N0") VND </h4></li>
                        }

                        @*<li> <span class="font-weight-bold">Màu:</span> <i class="fas fa-check bg-danger text-white"> </i> <i class="fas fa-check bg-warning text-white"></i> <i class="fas fa-check bg-success text-white"></i> <i class="fas fa-check bg-secondary text-white"></i></li>*@
                        <li class="pt-2"><span class="font-weight-bold"> Vận Chuyển:   <i class="fas fa-shipping-fast"></i></span><span class="form-control-sm text-secondary">Miễn phí vận chuyển(với đơn hàng trên 500.000đ)</span></li>
                        <li class="pt-3 ">
                            <span class="font-weight-bold">
                                Tình trạng: @if (number > 0)
                                {<span class="badge badge-success"> Còn hàng</span> }
                                else
                                { <span class="badge badge-danger"> Hết Hàng</span>}
                            </span>
                            <br><div class="pt-4"><span class=" font-weight-bold">Chi Tiết Sản Phẩm: </span></div>
                            <p class="text-secondary">@Html.Raw(detail)</p>
                        </li>
                        <li>
                            <span class="text-success  font-weight-bold"> Kho: @{int number1 = Model.number - Model.sold; } @number1 sản phẩm</span><br>
                            <span class="font-weight-bold"> Chọn Số Lượng: </span><span>
    <select class="form-select" aria-label="Default select example" w-25" id="sel1" onmousedown="if(this.options.length>8){this.size=8;}" onchange='this.size=0;' onblur="this.size=0;">
        @for (int i = 1; i <= Model.number; i++)
        {

            <option value="@i">@i</option>
        }
    </select>
    
</span>
                        </li>
                        <li>
                            <button onclick="addcart(@Model.ID)" class=" btn-button-cart bg-dark btn-lg"> Thêm Vào Giỏ Hàng</button>
                            <button onclick="addfavorite(@Model.ID)" class="btn-button-cart bg-danger btn-lg"><i class="far fa-heart"></i> Yêu Thích</button></a>
                        </li>
                    </ul>

                </div>
            </div>

        </div>
    </div>
</section>
</section>

<section class="container-fluid pt-3">
    <div class="container ">
        <div class="row">
            <div class="col-md-5 pt-5 borderr">
                <h4 class="font-weight-bold text-xanhduong">Sản Phẩm Liên Quan Cùng Loại</h4>
            </div><div class="col-md-7 pt-5 border-bottom ">
            </div>
            @Html.Action("cungloai", "Sanpham", new { catid = @Model.catid })
        </div>
    </div>

</section>